blank_issues_enabled: false
contact_links:
  - name: Dokumentasi stelloCMS
    url: https://github.com/stellocms/core/tree/main/doc
    about: Baca dokumentasi untuk informasi tentang penggunaan dan konfigurasi stelloCMS
  - name: Forum Komunitas
    url: https://github.com/stellocms/core/discussions
    about: Ajukan pertanyaan dan diskusikan stelloCMS dengan komunitas lainnya
  - email: hello@stellocms.com
    name: Kontak Tim Pengembang
    about: Hubungi tim pengembang stelloCMS untuk pertanyaan dan dukungan
